### ISSUE TITLE
Leaflet KML could not load icon

### ISSUE THREAD

**Issue by tt5430** [shramov/leaflet-plugins#131]
I tried to use Leaflet KML plugin the load the following simple place mark KML that has the href of the icon.  I have tried the following for the hrefs:
<href>icon21.png</href>
<href>kmls/icon21.png</href>
<href>http://localhost:8086/app/c2/kmls/icon21.png</href>
where: app/c2 is the codebase of the webapp.
kmls - is the directory where the kml and the icon are located

I saw the icon showed up on the map but it was the default icon and not the actual icon.  I have no ideas what is the problem.  Any help on this is greatly appreciated.

Regards,
Tam

**Comment by kalenkov** [comment]
please, reopen the bug

leaflet KML plugin does not understand placemark style placed within the Placemark element. Look at the simple example
http://katrine.lpi.ru/kalenkov/leaflet/style-kml.html
http://katrine.lpi.ru/kalenkov/leaflet/style.kml
There are two placemarks defined in the above KML file.

1) Placemark "place1"
Style of the placemark "place1" is defined outside the Placemark and the correct icon is shown on the map.

2) Placemark "place2"
Style of the placemark "place2" is defined within the Placemark and the leaflet shows default icon on the map instead of the icon defined in the KML file.

**Comment by brunob** [comment]
@kalenkov KML specs seems to disallow Style in Placemark tag : 

https://developers.google.com/kml/documentation/kmlreference#placemark

https://developers.google.com/kml/documentation/kml_tut#placemarks

or am i wrong ? (closing it, feel free to open if needed)

**Comment by kalenkov** [comment]
Noooooo

KML specs allows StyleSelector in Placemark tag
https://developers.google.com/kml/documentation/kmlreference#placemark

According to StyleSelector description
https://developers.google.com/kml/documentation/kmlreference#styleselector
StyleSelector is an abstract element and cannot be used directly in a KML file. It is the base type for the Style and StyleMap elements.

So I conclude that the Style element can be used in Placemark.

**Comment by brunob** [comment]
ok my bad, so we have to handle style defined in features now... patch welcome

**Comment by brunob** [comment]
@kalenkov @tt5430 can you test issue_131 branch ? it works for me

**Comment by kalenkov** [comment]
Yes, now it works as expected
http://katrine.lpi.ru/kalenkov/leaflet/style-kml-131.html
Many thanks!
