### ISSUE TITLE
Rotate can fail with custom markers because of undefined properties

### ISSUE THREAD

**Issue by bcg-didi** [shramov/leaflet-plugins#151]
I'm using the rotate plugin to rotate a custom marker.
Without rotation, *iconUrl* was the only required property. With rotation in place, that caused an error in *MarkerRotate.js* line 11 (var s undefined).
After setting *iconSize* and *iconAnchor* on the custom icon, it worked as expected.

**Comment by brunob** [comment]
Ok i see the bug. If you use a personal icon without iconAnchor + iconSize defined, we get an error since a and s vars are not defined here : 

https://github.com/shramov/leaflet-plugins/blob/master/layer/Marker.Rotate.js#L34

I can add a test on these lines, and put Leaflet default values if this properties are undefined. This will prevent the script to throw an error, but the result may not be perfect since we won't know your icon properties.

So, if you use a personal icon, you should define its iconAnchor and iconSize properties in order to get a perfect result.
