### ISSUE TITLE
On demand load of Bing metadata

### ISSUE THREAD

**Issue by Skrupellos** [shramov/leaflet-plugins#185]
Bing metadata gets loaded, when the Bing layer is added to a map, even when an other layer is active. Each metadata load creates a billable transaction, even if the layer might not be used. Therefore, the metadata should be loaded on demand, when the first tile is actually requested.

**Comment by brunob** [comment]
Will try to have a look at this enhancement, anyway feel free to provide a patch :)

**Comment by brunob** [comment]
I you look at network requests, you can see that the call to metadata is done only one time when map is loading.

We can try to change bing script in order to call metadata in `onAdd()` method (see below patch), this allow to call metadata only when the layer is showed, but this generate a call *every time* the layer is showed... so more calls if the user switch this one on/off many times. I think actual process is better, no ?

``` diff
diff --git a/layer/tile/Bing.js b/layer/tile/Bing.js
index b3a5b96..36ad5b8 100644
--- a/layer/tile/Bing.js
+++ b/layer/tile/Bing.js
@@ -12,7 +12,11 @@ L.BingLayer = L.TileLayer.extend({
 		this._key = key;
 		this._url = null;
 		this.meta = {};
+	},
+	
+	onAdd: function (map) {
 		this.loadMetadata();
+		L.TileLayer.prototype.onAdd.apply(this, [map]);
 	},
 
 	tile2quad: function(x, y, z) {
```

**Comment by Skrupellos** [comment]
Thanks for the hint. I made a PR with a "meta data load guard" (and removed the raw meta data from the object).
