### ISSUE TITLE
GridLayer.GoogleMutant

### ISSUE THREAD

**Issue by IvanSanchez** [shramov/leaflet-plugins#250]
This is a "letting you know" more than a bug or feature request, but anyway.

I've borrowed your code for the Google layer, added some DOM mutation observers here and there, some DOM wrangling, and made this: https://gitlab.com/IvanSanchez/Leaflet.GridLayer.GoogleMutant

This has the potential of solving #205, #209 and the dreaded zoom/pan lag (#111 and duplicates).

I've added it to the Leaflet plugins list. Letting you know in case you want to switch to GoogleMutant and worry less about maintaining your current code.

**Comment by brunob** [comment]
Thx a lot for pointing this to me @IvanSanchez :)

As i already said in many comments i'm _bored_ to maintain the google layer script, and since your script work better i think i could redirect users to your repo and forget #175. Plus it would avoid to have work done on two libs that provide the same functionality.

**Comment by IvanSanchez** [comment]
Sounds good! :-)

**Comment by pke** [comment]
@IvanSanchez Any reason this is not on github?

**Comment by IvanSanchez** [comment]
@pke I just like gitlab too.

**Comment by taufik946** [comment]
hey IvanSanchez thanks on your plugin, but I had problems when I want to enter json data into your script html, please help me thanks

**Comment by IvanSanchez** [comment]
@taufik946 [compliment] [out-of-context unspecified problem you don't really care about] [statement of urgency]

See http://www.catb.org/esr/faqs/smart-questions.html
