### ISSUE TITLE
Google TOS?

### ISSUE THREAD

**Issue by piotryordanov** [shramov/leaflet-plugins#48]
According to [this](http://code.google.com/intl/fr/apis/maps/terms.html#section_10_1), one should not be able to use the map outside of google's tools.

Yet, I can still do:

```
  var road = new L.Google("ROADMAP");
```

or

```
  var road = new L.Google("SATELLITE");
```

And get access to the map with either street or satellite view.

So I'm wondering, how are you doing it? By using the script, would I be actually breaking any rule?

Cheers, and thanks for this great tool mate!

**Comment by smitchell** [comment]
I'm going to raise this issue at work. The lack of a Google plugin is a deal breaker for Leaflet at my job. We depend on Google to create courses that "snap to roads" with Google's directions. We do the same thing with MapQuest for OSM (we dropped Bing due to bugs). I would love to consolidate all our code into a single code base then let the user choose between Google, Bing, and OSM.

**Comment by pke** [comment]
Any news on that? Consider switching from Mapbox to Google Maps because the pricing tiers of Mapbox make no sense at all.

**Comment by brunob** [comment]
@pke see #250

**Comment by brunob** [comment]
We can finally close this one since #250 :)
