### ISSUE TITLE
Yandex : traffic overlaps map markers.

### ISSUE THREAD

**Issue by 10litrov** [shramov/leaflet-plugins#97]
When using Yandex Traffic layer as overlay (like in example), it overlaps any markers on map.

**Comment by brunob** [comment]
This bug is due to the way yandex script is done by applying a second container for yandex elements and put this second container out of leaflet panes. This script may need a refactoring but i don't plan to do it, feel free to provide pull requests for it :)

Anyway, have you tried to add the layers without overlay:true option, without it i can show yandex traffic and my leaflet markers.

**Comment by er24scorpion** [comment]
Without overlay:true traffic not shown. I have no idea how find solution of problem traffic panel. Help, please.

**Comment by brunob** [comment]
Closing this old issue since nobody is working on it. Feel free to provide a pull req for that :)

**Comment by johnd0e** [comment]
BTW, now overlay is completely broken #287.
But Traffic is possible to show without overlay:
```
var ytraffic = new L.Yandex("map", {traffic:true});
map.addLayer(ytraffic);

```
